name: Build .deb (Theos)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.xm'
      - '**/*.mm'
      - '**/*.m'
      - '**/*.h'
      - 'Makefile'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      THEOS: ${{ runner.temp }}/theos

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install base deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential fakeroot git perl curl ca-certificates zip unzip rsync libtinfo5

      - name: Install ldid (Procursus)
        run: |
          set -eux
          curl -L -o ldid https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_linux_x86_64
          sudo install -m755 ldid /usr/local/bin/ldid

      - name: Fetch Theos
        run: |
          set -eux
          git clone --recursive https://github.com/theos/theos.git "$THEOS"

      - name: Fetch toolchain (Linux → iPhoneOS)
        run: |
          set -eux
          mkdir -p "$THEOS/toolchain"
          urls=(
            https://github.com/theos/toolchain-linux/releases/latest/download/iphoneos-linux-toolchain.tar.xz
            https://github.com/theos/toolchain-linux/releases/latest/download/iphoneos-clang-toolchain.tar.xz
            https://github.com/theos/toolchain-linux/releases/latest/download/linux-ios-toolchain.tar.xz
          )
          got=""
          for u in "${urls[@]}"; do
            echo "Attempting: $u"
            curl -fL "$u" -o /tmp/ios-toolchain.tar.xz && got="yes" && break || true
          done
          if [ -z "$got" ]; then
            echo "Could not download toolchain from known URLs"; exit 1
          fi
          tar -xJf /tmp/ios-toolchain.tar.xz -C "$THEOS/toolchain"

      - name: Fetch iOS SDKs
        run: |
          set -eux
          git clone --depth=1 https://github.com/theos/sdks.git "$THEOS/sdks"

      - name: Pick older iOS SDK for Linux Clang
        run: |
          set -eux
          for ver in 14.5 14.4 14.2 13.7 13.0; do
            C="$THEOS/sdks/iPhoneOS${ver}.sdk"
            if [ -d "$C" ]; then
              echo "Using SDK: $C"
              echo "THEOS_PLATFORM_SDK_ROOT=$C" >> $GITHUB_ENV
              exit 0
            fi
          done
          echo "No 14.x/13.x SDK found. Available SDKs:"; ls -la "$THEOS/sdks"; exit 1

      - name: Detect tweak directory
        id: finddir
        run: |
          set -eux
          if [ -f Makefile ]; then
            echo "dir=." >> $GITHUB_OUTPUT
            exit 0
          fi
          d=$(grep -RIl --include=Makefile -e '^TWEAK_NAME[[:space:]]*:=' -e '^BUNDLE_NAME[[:space:]]*:=' || true | head -n1)
          if [ -n "$d" ]; then
            echo "dir=$(dirname "$d")" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "No Makefile found"; exit 1

      - name: Build .deb (rootless)
        working-directory: ${{ steps.finddir.outputs.dir }}
        run: |
          set -eux
          make clean
          make package
          mkdir -p "$GITHUB_WORKSPACE/out"
          cp -v packages/*.deb "$GITHUB_WORKSPACE/out/" || true

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: w2like-deb
          path: out/*.deb
